/**
 * Generated by scripts/generate-openai-audio.ts.
 * Voice: marin; model: gpt-4o-mini-tts; speed: 0.88.
 */
export const generatedAudioPaths: Record<string, string> = {
  "root-xue": "/zimai-mandarin/audio/openai/root-xue.mp3",
  "root-dian": "/zimai-mandarin/audio/openai/root-dian.mp3",
  "root-kan": "/zimai-mandarin/audio/openai/root-kan.mp3",
  "root-tian-expansion": "/zimai-mandarin/audio/openai/root-tian-expansion.mp3",
  "root-ming-expansion": "/zimai-mandarin/audio/openai/root-ming-expansion.mp3",
  "root-you-friend-expansion": "/zimai-mandarin/audio/openai/root-you-friend-expansion.mp3",
  "root-xi-expansion": "/zimai-mandarin/audio/openai/root-xi-expansion.mp3",
  "root-lao-expansion": "/zimai-mandarin/audio/openai/root-lao-expansion.mp3",
  "word-xuesheng": "/zimai-mandarin/audio/openai/word-xuesheng.mp3",
  "word-xuexiao": "/zimai-mandarin/audio/openai/word-xuexiao.mp3",
  "word-xuexi": "/zimai-mandarin/audio/openai/word-xuexi.mp3",
  "word-dianhua": "/zimai-mandarin/audio/openai/word-dianhua.mp3",
  "word-dianshi": "/zimai-mandarin/audio/openai/word-dianshi.mp3",
  "word-dianying": "/zimai-mandarin/audio/openai/word-dianying.mp3",
  "word-kanshu": "/zimai-mandarin/audio/openai/word-kanshu.mp3",
  "word-kanjian": "/zimai-mandarin/audio/openai/word-kanjian.mp3",
  "word-word-tian-jintian-expansion": "/zimai-mandarin/audio/openai/word-word-tian-jintian-expansion.mp3",
  "word-word-tian-mingtian-expansion": "/zimai-mandarin/audio/openai/word-word-tian-mingtian-expansion.mp3",
  "word-word-tian-tianqi-expansion": "/zimai-mandarin/audio/openai/word-word-tian-tianqi-expansion.mp3",
  "word-word-tian-tiantian-expansion": "/zimai-mandarin/audio/openai/word-word-tian-tiantian-expansion.mp3",
  "word-word-ming-mingzi-expansion": "/zimai-mandarin/audio/openai/word-word-ming-mingzi-expansion.mp3",
  "word-word-you-pengyou-expansion": "/zimai-mandarin/audio/openai/word-word-you-pengyou-expansion.mp3",
  "word-word-xi-xihuan-expansion": "/zimai-mandarin/audio/openai/word-word-xi-xihuan-expansion.mp3",
  "word-word-lao-laoshi-expansion": "/zimai-mandarin/audio/openai/word-word-lao-laoshi-expansion.mp3"
}
