import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { content } from '../src/content/contentData'
import type { Character, Word } from '../src/content/types'

const repositoryRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const outputDirectory = join(repositoryRoot, 'public/audio/openai')
const manifestPath = join(repositoryRoot, 'src/content/generatedAudio.ts')
const model = 'gpt-4o-mini-tts'
const voice = 'marin'
const speed = 0.88
const isForce = process.argv.includes('--force')
const isAll = process.argv.includes('--all')

function requireApiKey() {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY is not set. Keep it in the local environment; never commit it to the app.')
  }
  return process.env.OPENAI_API_KEY
}

function selectTargets() {
  const hskOneWords = content.words.filter((word) => word.hskLevel === 'HSK 1')
  const words = isAll ? hskOneWords : hskOneWords.slice(0, 20)
  const characterIds = new Set(words.flatMap((word) => word.rootCharacterIds))
  const characters = content.characters.filter((character) => characterIds.has(character.id))
  return [...characters, ...words]
}

function inputFor(item: Character | Word) {
  return item.hanzi
}

function filenameFor(audioKey: string) {
  return `${audioKey.replace(/[^a-zA-Z0-9_-]/g, '-')}.mp3`
}

async function generateAudio(item: Character | Word, apiKey: string) {
  const filename = filenameFor(item.audioKey)
  const outputPath = join(outputDirectory, filename)
  try {
    await readFile(outputPath)
    if (!isForce) return { item, filename, skipped: true }
  } catch {
    // The asset is missing, so generate it below.
  }

  const response = await fetch('https://api.openai.com/v1/audio/speech', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model,
      voice,
      input: inputFor(item),
      instructions: 'Speak only the supplied Mandarin Chinese text in clear, standard Putonghua. Preserve every tone precisely. Use a warm, natural, learner-friendly pace and clean studio pronunciation.',
      response_format: 'mp3',
      speed,
    }),
  })

  if (!response.ok) {
    throw new Error(`OpenAI TTS request failed for ${item.hanzi} (${response.status})`)
  }

  const audio = Buffer.from(await response.arrayBuffer())
  await writeFile(outputPath, audio)
  return { item, filename, skipped: false }
}

async function main() {
  const apiKey = requireApiKey()
  const targets = selectTargets()
  await mkdir(outputDirectory, { recursive: true })

  const generated: Record<string, string> = {}
  let created = 0
  let skipped = 0

  for (const target of targets) {
    const result = await generateAudio(target, apiKey)
    generated[target.audioKey] = `/zimai-mandarin/audio/openai/${result.filename}`
    if (result.skipped) skipped += 1
    else {
      created += 1
      console.log(`Generated ${target.hanzi} (${target.audioKey})`)
    }
  }

  const manifest = `/**\n * Generated by scripts/generate-openai-audio.ts.\n * Voice: ${voice}; model: ${model}; speed: ${speed}.\n */\nexport const generatedAudioPaths: Record<string, string> = ${JSON.stringify(generated, null, 2)}\n`
  await writeFile(manifestPath, manifest)
  console.log(`OpenAI audio ready: ${created} generated, ${skipped} already present, ${targets.length} total targets.`)
}

void main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : 'OpenAI audio generation failed.')
  process.exitCode = 1
})
